transport/urls.py
from django.urls import path
from . import views

app_name = 'transport'

urlpatterns = [
   path('', views.main_page_tran, name="mainpage"),
   path('mailman/', views.second_page_tran, name="mailman"),
   path('technician/', views.main_page_tech, name="technician"),
   path('<data>/', views.first_change, name="firstchange"),
   


]   

user/urls.py
from django.urls import path
from . import views

app_name = 'profile'

urlpatterns = [
   path('', views.mainprofile, name="menu"),
 #  path('profile/', views.updateprofile, name="updateprofile"),
   path('<ud>', views.orderstatus, name="orderstatus"),
   path('done/<data>', views.done, name="lastaction"),
]

weblab/urls.py
from django.contrib import admin
from django.urls import include, path
from instruments import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab/', include('instruments.urls')),
    path('userprofile/', include('user.urls')),
    path('transport/', include('transport.urls')),
    path('technician/', include('technician.urls')),
    path('',views.mainlab )
]

#http://127.0.0.1:8000/lab

instruments/models.py
from django.db import models
from user.models import User
from enum import Enum



# Phonebrand table represents all the popular phone brands in israel and give us the option to illustrate the web with brand pics 

class Phonebrand(models.Model):
   brand = models.CharField(max_length=100, null=False)
   logo = models.ImageField(null=True, blank=True)
   
   def __str__(self):
      return self.brand


# Phonetype table represents all the popular phone types in israel connected to specific brand and give us the option to illustrate the web with gadget pics 

class Phonetype(models.Model):
   brand = models.ForeignKey(Phonebrand,on_delete=models.CASCADE)
   type = models.CharField(max_length=100, null=False)
   image =  models.ImageField(null=True, blank=True)

   def __str__(self):
      return self.brand.brand +","+  self.type

# represents the popular phone by phone type and brand make the serch more easy to execute 

class Phone(models.Model):
   type= models.ForeignKey(Phonetype,on_delete=models.CASCADE)
   device = models.CharField(max_length=100, null=False)

   def __str__(self):
      return self.device +","+  self.type.type


# here the web owner insert the popular Malfunction types he can ofer

class Malfunction_type(models.Model):
   Malfunction = models.CharField(max_length=100)

   def __str__(self):
      return self.Malfunction


class status_order_type(Enum):
   await_for_mail_man = 1
   in_process = 2
   phone_ready_for_delivery = 3
   phone_ready_mailman_will_arrive_soon = 4
   order_done = 5


#that table grouping Phone,Malfunction_type,user for represent the order

class Malfunction(models.Model):
   
   
   class StatusType(models.IntegerChoices):
        await_for_mail_man = 1, "await for mail man"
        in_process = 2, "in process"
        phone_ready_for_delivery = 3, 'phone ready for delivery'
        phone_ready_mailman_will_arrive_soon = 4, 'phone ready mailman will arrive soon'
        order_done = 5, 'order done'


   phone= models.ForeignKey(Phone,on_delete=models.CASCADE)
   Malfunction_type= models.ForeignKey(Malfunction_type,on_delete=models.CASCADE)
   user= models.ForeignKey(User,on_delete=models.CASCADE)
   status = models.PositiveIntegerField(null= True, choices=StatusType.choices)
   request_date = models.DateField(auto_now_add=True)

   def __str__(self):
         return self.user.username +","+ self.Malfunction_type.Malfunction +","+  self.phone.device +","+ str(self.request_date)

   def get_Type(self):
        for choice in self.StatusType:
            if self.type == choice.value:
                return choice.label
        return 'NO TYPE'

transport/models.py
from django.db import models

transport/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from instruments.models import Malfunction
from django.contrib import messages
from django.db.models import Q
 
# this function is for the first delivery afther the costumer make a order the mail man need to go to the place he insert to the web and take the phone 
def main_page_tran(request):
    Customers = Malfunction.objects.all()
    context = {
        'customers' :Customers,
        'action' : 'staff'

    }
    return  render(request,'firsttable.html',context)
     
def first_change(request,data):
    data = data.split(',')
    num =  int(data[2]) +1
    Customers = Malfunction.objects.filter( user_id = data[0], id = data[1]).update(status = num)
    messages.success(request, 'Nice work,The order was transferred to another department ')
    return redirect('/')    

#this function is for the second delivery the mail man take the phone from the technician and deliver the phone back to the cosumer
def second_page_tran(request):
    Customers = Malfunction.objects.filter(Q(status = '1') | Q(status ='3'))
    context = {
        'customers' :Customers,
        'action' : 'staff'
    }
    return  render(request,'firsttable.html',context)

def main_page_tech(request):
    Customers = Malfunction.objects.filter(status = '2')
    context = {
        'customers' :Customers,
        'action' : 'staff'

    }
    return  render(request,'firsttable.html',context)

transport/templates/firsttable.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Tables - SB Admin</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
        <link href="{%static 'css/styles.css'%}" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    </head>    

                            <li class="breadcrumb-item active"></li>
                        </ol>
                        <div class="card mb-4">
                            <div class="card-header">
                                <i class="fas fa-table me-1"></i>
                                costomers list
                            </div>
                                  
                            <div class="card mb-4">
                                <div class="card-header">
                                    <i class="fas fa-table me-1"></i>
                                    <div style="text-align: center;">
                                        <h4> click to filter</h4>
                                        <a href="{% url 'transport:mainpage' %}" class="mybutton" style="background-color: rgb(7, 84, 90);">All</a>                                                                               
                                        <a href="{% url 'transport:mailman' %}" class="mybutton" style="background-color: rgb(101, 2, 95);">mailman</a>                                      
                                        <a href="{% url 'transport:technician' %}" class="mybutton" style="background-color: brown;">technician</a>                                                                               
                                    </div>
                                </div>


                            <div class="card-body">
                                <table id="datatablesSimple">
                                    <thead>
                                        <tr>
                                            <th>שם</th>
                                            <th>תקלה</th>
                                            <th>כתובת</th>
                                            <th>מכשיר</th>
                                            <th>תאריך בקשה</th>
                                            <th>מצב הזמנה</th>
                                            <th>link</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Name</th>
                                            <th>status</th>
                                            <th>address</th>
                                            <th>Age</th>
                                            <th>phonenumber</th>
                                            <th>link</th>
                                            <th>status</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                    {%if user.Role == 1 or user.Role == 2 or user.Role == 3 or action == 'user' %}
                                        {%for costomer in customers%}
                                        <tr>
                                            <td>{{costomer.user.username}}
                                        
                                            </td>
                                            
                                            <td>{{costomer.Malfunction_type.Malfunction}}</td>
                                            <td>{{costomer.user.Full_address}}</td>
                                            <td>{{costomer.phone.device}}</td>
                                            <td>{{costomer.request_date}}</td>
                                            <td>{{costomer.get_status_display}}</td>
                                            {% if user.Role == 1 and costomer.status == 1 or user.Role == 3 and costomer.status == 1  or user.Role == 3 and costomer.status == 3 or user.Role == 1 and costomer.status == 3%}
                                                <td><a href="/transport/{{costomer.user_id}},{{costomer.id}},{{costomer.status}}" class="mybutton" style="background-color: rgb(101, 2, 95);"> choose</a></td>                                       
                                            {% else %} 
                                            {% if user.Role == 2 and costomer.status == 2 or user.Role == 3 and costomer.status == 2 %}
                                                <td><a href="/transport/{{costomer.user_id}},{{costomer.id}},{{costomer.status}}" class="mybutton" style="background-color: brown;">choose</a></td>                                       
                                            {% else %}
                                            {% if  action == 'user' and costomer.status == 4 %}
                                                <td><a href="/transport/{{costomer.user_id}},{{costomer.id}},{{costomer.status}}" button type="submit" class="btn btn-outline-dark"> confirm the end of the process</a></td>                                       
                                            {% else %}
                                                <td></td>                                       
                                            {% endif %}
                                            {% endif %}
                                            {% endif %}
                    
                                        </tr>
                                        {% endfor %}
                                    {%else%}
                                        <h1> Staff memebers only </h1>
                                    {% endif %}
                                    
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </main>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{%static 'js/scripts.js'%}"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
        <script src="{%static 'js/datatables-simple-demo.js'%}"></script>
        <script>                                                
            // Get the button, and when the user clicks on it, execute myFunction
            document.getElementById("myBtn").onclick = function() {myFunction()};
            
            /* myFunction toggles between adding and removing the show class, which is used to hide and show the dropdown content */
            function myFunction() {
              document.getElementById("myDropdown").classList.toggle("show");
            }
        </script>
    
    </body>

    {% endblock%}