instruments/urls.py
from django.urls import path
from . import views,user_func

app_name = 'lab'

urlpatterns = [
   path('search/', views.search, name="search"),
   path('login/', user_func.elogin, name="login"),
   path('logout/', user_func.elogout, name="logout"),
   path('register/', user_func.eregister, name="register"),
   path('lab/', views.brand, name="brand"),
   path('lab/<br>/', views.type, name="type"),
   path('lab/<br>/hitch', views.useraction, name="data"),
   path('lab/<br>/<mu>/<ui>', views.add_data, name="add_data"),



]

user/urls.py
from django.urls import path
from . import views

app_name = 'profile'

urlpatterns = [
   path('', views.mainprofile, name="menu"),
 #  path('profile/', views.updateprofile, name="updateprofile"),
   path('<ud>', views.orderstatus, name="orderstatus"),
   path('done/<data>', views.done, name="lastaction"),
]

weblab/urls.py
from django.contrib import admin
from django.urls import include, path
from instruments import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab/', include('instruments.urls')),
    path('userprofile/', include('user.urls')),
    path('transport/', include('transport.urls')),
    path('technician/', include('technician.urls')),
    path('',views.mainlab )
]

#http://127.0.0.1:8000/lab

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

  <style>

.center {
    margin: auto;
    width: 220%;
    padding: 120px;
    text-align: center;
    }

    .backboard {
      margin: auto;
      width: 70%;
      padding: 75px;
      text-align: center;
      background-color: aliceblue;
    }


    .mybutton {
        display: inline-block;
        background: #000;
        color: #fff;
        border: none;
        padding: 10px 20px;
        margin: 10px;
        border-radius: 30px;
        cursor: pointer;
        text-decoration: none;
        font-size: 15px;
        font-family: inherit;
}
</style>

    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
</head>
<body  style="background-color:black">
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">home page</a>
          
              <!-- login register -->
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
              <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                   hello: {{ user.username }}!
                </button>
                <ul class="dropdown-menu dropdown-menu-dark">
                  <li><a class="dropdown-item active" href="{% url 'profile:menu' %}" >איזור אישי                   
                  </a>
                  </li>
                  <li><a class="dropdown-item active" href="{% url 'lab:logout' %}" >התנתק</a> </li>
                </ul>

        
              </div>
                {% else %}
                  <li><a class="mybutton" href="{% url 'lab:register' %}" role="button">register</a>
                  <li><a class="mybutton" href="{% url 'lab:login' %}" role="button">log in</a>                  
                {% endif %}
              </ul>
              <!-- end login register-->
          
          
              <form class="d-flex" role="search" action="{% url 'lab:search' %}" >
                <input name="search" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="mybutton" type="submit">Search</button>
            
            </form>
          </div>
        </div>
      </nav>
      <br>
      {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div class="text-light bg-dark">{{ message }}</div>
    {% endfor %}
</ul>
{% endif %}
{% block title %} {% endblock %}
{% block content %}
{% endblock %}
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>