instruments/urls.py
from django.urls import path
from . import views,user_func

app_name = 'lab'

urlpatterns = [
   path('search/', views.search, name="search"),
   path('login/', user_func.elogin, name="login"),
   path('logout/', user_func.elogout, name="logout"),
   path('register/', user_func.eregister, name="register"),
   path('lab/', views.brand, name="brand"),
   path('lab/<br>/', views.type, name="type"),
   path('lab/<br>/hitch', views.useraction, name="data"),
   path('lab/<br>/<mu>/<ui>', views.add_data, name="add_data"),



]

transport/urls.py
from django.urls import path
from . import views

app_name = 'transport'

urlpatterns = [
   path('', views.main_page_tran, name="mainpage"),
   path('mailman/', views.second_page_tran, name="mailman"),
   path('technician/', views.main_page_tech, name="technician"),
   path('<data>/', views.first_change, name="firstchange"),
   


]   

user/urls.py
from django.urls import path
from . import views

app_name = 'profile'

urlpatterns = [
   path('', views.mainprofile, name="menu"),
 #  path('profile/', views.updateprofile, name="updateprofile"),
   path('<ud>', views.orderstatus, name="orderstatus"),
   path('done/<data>', views.done, name="lastaction"),
]

weblab/urls.py
from django.contrib import admin
from django.urls import include, path
from instruments import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab/', include('instruments.urls')),
    path('userprofile/', include('user.urls')),
    path('transport/', include('transport.urls')),
    path('technician/', include('technician.urls')),
    path('',views.mainlab )
]

#http://127.0.0.1:8000/lab

instruments/models.py
from django.db import models
from user.models import User
from enum import Enum



# Phonebrand table represents all the popular phone brands in israel and give us the option to illustrate the web with brand pics 

class Phonebrand(models.Model):
   brand = models.CharField(max_length=100, null=False)
   logo = models.ImageField(null=True, blank=True)
   
   def __str__(self):
      return self.brand


# Phonetype table represents all the popular phone types in israel connected to specific brand and give us the option to illustrate the web with gadget pics 

class Phonetype(models.Model):
   brand = models.ForeignKey(Phonebrand,on_delete=models.CASCADE)
   type = models.CharField(max_length=100, null=False)
   image =  models.ImageField(null=True, blank=True)

   def __str__(self):
      return self.brand.brand +","+  self.type

# represents the popular phone by phone type and brand make the serch more easy to execute 

class Phone(models.Model):
   type= models.ForeignKey(Phonetype,on_delete=models.CASCADE)
   device = models.CharField(max_length=100, null=False)

   def __str__(self):
      return self.device +","+  self.type.type


# here the web owner insert the popular Malfunction types he can ofer

class Malfunction_type(models.Model):
   Malfunction = models.CharField(max_length=100)

   def __str__(self):
      return self.Malfunction


class status_order_type(Enum):
   await_for_mail_man = 1
   in_process = 2
   phone_ready_for_delivery = 3
   phone_ready_mailman_will_arrive_soon = 4
   order_done = 5


#that table grouping Phone,Malfunction_type,user for represent the order

class Malfunction(models.Model):
   
   
   class StatusType(models.IntegerChoices):
        await_for_mail_man = 1, "await for mail man"
        in_process = 2, "in process"
        phone_ready_for_delivery = 3, 'phone ready for delivery'
        phone_ready_mailman_will_arrive_soon = 4, 'phone ready mailman will arrive soon'
        order_done = 5, 'order done'


   phone= models.ForeignKey(Phone,on_delete=models.CASCADE)
   Malfunction_type= models.ForeignKey(Malfunction_type,on_delete=models.CASCADE)
   user= models.ForeignKey(User,on_delete=models.CASCADE)
   status = models.PositiveIntegerField(null= True, choices=StatusType.choices)
   request_date = models.DateField(auto_now_add=True)

   def __str__(self):
         return self.user.username +","+ self.Malfunction_type.Malfunction +","+  self.phone.device +","+ str(self.request_date)

   def get_Type(self):
        for choice in self.StatusType:
            if self.type == choice.value:
                return choice.label
        return 'NO TYPE'

instruments/forms.py
from django.forms import ModelForm
from user.models import User
from django.contrib.auth.forms import UserCreationForm

# i pull the Original User Form and added to the Form my extensions 

class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','first_name','last_name','email','age','City','Full_address','Postal_Code','Phonenumber')


 

instruments/views.py
from urllib import request
from django.http import HttpResponse
from django.shortcuts import redirect, render
from instruments.models import Malfunction, Phonebrand, Phonetype,Phone,Malfunction_type
from django.contrib.auth.decorators import login_required
from django.contrib import messages

def mainlab(request):
    context = {
        'brandlist': 'none'
    }        
    return render(request, 'brand.html', context)




# here i show to the costumers all the brands i have to ofer
def brand(request):
    brandlist = Phonebrand.objects.all()
    context = {
        'brandlist': brandlist,
    }
    return render(request, 'brand.html', context)


# here i show to the costumers all the phone types i have to ofer
@login_required
def type(request,br):
    typelist = Phonetype.objects.filter(brand = br)
    device = Phone.objects.all()
    context = {
        'typelist': typelist,
        'phones':device,

    }
    return render(request, 'phonetype.html', context)

# give the costumer the option to choose the problem he have 
def useraction(request,br):
    hitch = Malfunction_type.objects.all()
    context = {
        'hitches' : hitch,
        'type' : br
    }
    return  render(request,'malfu.html',context)


def search(request):
    send =  request.GET.get('search')
    result = Phone.objects.filter(device__contains = send) 
    context = {
        'results':result,
        'name':'search'
    }
    return render(request,'phonetype.html', context)


# insert the data to Malfunction table 
def add_data(request,br,mu,ui):
    userid = ui
    Status = 1
    malfunction = Malfunction(phone_id = br,Malfunction_type_id = mu, user_id = userid, status = Status)
    malfunction.save()
    messages.success(request, 'your request accepted')
    return redirect('/') 

instruments/templates/brand.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  

{% if brandlist == "none" %}
<div class="center">   
    <div class="row row-cols-2 row-cols-lg-5 g-2 g-lg-3">
      <div class="col">
        <div class="p-3 border bg-light">
          <svg xmlns="http://www.w3.org/2000/svg" width="500" height="300" fill="currentColor" class="bi bi-shop" viewBox="0 0 16 16">
            <path d="M2.97 1.35A1 1 0 0 1 3.73 1h8.54a1 1 0 0 1 .76.35l2.609 3.044A1.5 1.5 0 0 1 16 5.37v.255a2.375 2.375 0 0 1-4.25 1.458A2.371 2.371 0 0 1 9.875 8 2.37 2.37 0 0 1 8 7.083 2.37 2.37 0 0 1 6.125 8a2.37 2.37 0 0 1-1.875-.917A2.375 2.375 0 0 1 0 5.625V5.37a1.5 1.5 0 0 1 .361-.976l2.61-3.045zm1.78 4.275a1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0 1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0 1.375 1.375 0 1 0 2.75 0V5.37a.5.5 0 0 0-.12-.325L12.27 2H3.73L1.12 5.045A.5.5 0 0 0 1 5.37v.255a1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0zM1.5 8.5A.5.5 0 0 1 2 9v6h1v-5a1 1 0 0 1 1-1h3a1 1 0 0 1 1 1v5h6V9a.5.5 0 0 1 1 0v6h.5a.5.5 0 0 1 0 1H.5a.5.5 0 0 1 0-1H1V9a.5.5 0 0 1 .5-.5zM4 15h3v-5H4v5zm5-5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1v-3zm3 0h-2v3h2v-3z"/>
          </svg>            <br></br>
            <a class="mybutton" href="{% url 'lab:brand' %}"> lab </a>
            <hr></hr>
              add a request for fixing your phone 
          </div>
    </div>



    <div class="col">
      <div class="p-3 border bg-light">
        <svg xmlns="http://www.w3.org/2000/svg" width="500" height="300" fill="currentColor" class="bi bi-file-earmark-lock2" viewBox="0 0 16 16">
          <path d="M10 7v1.076c.54.166 1 .597 1 1.224v2.4c0 .816-.781 1.3-1.5 1.3h-3c-.719 0-1.5-.484-1.5-1.3V9.3c0-.627.46-1.058 1-1.224V7a2 2 0 1 1 4 0zM7 7v1h2V7a1 1 0 0 0-2 0z"/>
          <path d="M14 14V4.5L9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2zM9.5 3A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5v2z"/>
        </svg>      <br></br>
      <a class="mybutton" href="{% url 'transport:mainpage' %}"> Employees area </a>    
      <hr></hr>
        this area available only for laborers users 
      </div>
  </div>
</div>

    
    
{%else%}
 <div class="row row-cols-1 row-cols-md-5 g-4">
         {% for brand in brandlist %}    
         <div class="col">
           <div class="card">
             <img style="width:280px;height:150px" src="{% static 'images/web_uplouds/'%}{{ brand.logo }}" class="card-img-top" alt="...">
             <div class="card-body">
               <h5 class="card-title">{{ brand.brand }}</h5>
               <p class="card-text"></p>
               <a href="{{ brand.id }}/" class="btn btn-danger">המשך</a>
             </div>
           </div>
         </div>
         {% endfor %}
     </div>
{%endif%}     
{% endblock%}

instruments/templates/malfu.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<style>
    .Board {
        width: 30%;
        float:left;
        padding: 3%;
        text-align: center;
        background-color: aliceblue;
        margin: 10px;
      }
    </style>
    {%for hitch in hitches %}
    <div class="Board">
        <h2>problem</h2>
        <hr></hr>
        <h5>{{hitch.Malfunction }}</h5> 
        <hr></hr>
        <h3>price:</h3>
        <a class="mybutton" role="button" href="/lab/lab/{{ type }}/{{ hitch.id }}/{{user.id}}"> none </a>    
    </div>
    {% endfor %}
    {% endblock%}
    

instruments/templates/phonetype.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% if name == 'search' %} 
{% for result in results %}
<a style="color:rgb(244, 240, 240)" href="/lab/lab/{{ result.id }}/hitch"> {{result.device}} </a>
<br></br>
{% endfor %}
{% else %} 
<div class="row row-cols-1 row-cols-md-5 g-4">
    {% for type in typelist %}    
    <div class="col">
      <div class="card">
        <img style="width:280px;height:150px" src="{% static 'images/web_uplouds/'%}{{ type.image }}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{ type.type}}</h5>
          <p class="card-text"></p>
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              דגמים
            </button>
            <ul class="dropdown-menu dropdown-menu-dark">
              {% for phone in phones %}
                {% if phone.type_id == type.id %}
                  <li><a class="dropdown-item active"  href="/lab/lab/{{ phone.id }}/hitch">{{ phone.device }}</a></li>
                {% endif %}
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
    {% endif %}
  </div>
{% endblock%}